---
- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/model/tugbot/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
- ros_topic_name: "/odom"
  gz_topic_name: "/model/tugbot/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "/tugbot/scan_front/scan_front"
  gz_topic_name: "/world/world_demo/model/tugbot/link/scan_front/sensor/scan_front/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
- ros_topic_name: "/tugbot/scan_back/scan_back"
  gz_topic_name: "/world/world_demo/model/tugbot/link/scan_back/sensor/scan_back/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
- ros_topic_name: "/tugbot/scan_omni/scan_omni"
  gz_topic_name: "/world/world_demo/model/tugbot/link/scan_omni/sensor/scan_omni/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
- ros_topic_name: "/scan/points"
  gz_topic_name: "/world/world_demo/model/tugbot/link/scan_omni/sensor/scan_omni/scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "/sensor_contact/scan"
  gz_topic_name: "/world/world_demo/model/tugbot/link/gripper/sensor/sensor_contact/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/imu"
  gz_topic_name: "/world/world_demo/model/tugbot/link/imu_link/sensor/imu/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/world_demo/model/tugbot/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS
- ros_topic_name: "/tf"
  gz_topic_name: "/model/tugbot/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
# - ros_topic_name: "/tf_static"
#   gz_topic_name: "/model/diff_drive/pose_static"
#   ros_type_name: "tf2_msgs/msg/TFMessage"
#   gz_type_name: "gz.msgs.Pose_V"
#   direction: GZ_TO_ROS



# /world/world_demo/model/tugbot/link/camera_back/sensor/color/camera_info
# /world/world_demo/model/tugbot/link/camera_back/sensor/color/image
# /world/world_demo/model/tugbot/link/camera_back/sensor/depth/camera_info
# /world/world_demo/model/tugbot/link/camera_back/sensor/depth/depth_image
# /world/world_demo/model/tugbot/link/camera_back/sensor/depth/depth_image/points
# /world/world_demo/model/tugbot/link/camera_front/sensor/color/camera_info
# /world/world_demo/model/tugbot/link/camera_front/sensor/color/image
# /world/world_demo/model/tugbot/link/camera_front/sensor/depth/camera_info
# /world/world_demo/model/tugbot/link/camera_front/sensor/depth/depth_image
# /world/world_demo/model/tugbot/link/camera_front/sensor/depth/depth_image/points


# Color camera image
- ros_topic_name: "/camera_back/color/image_raw"
  gz_topic_name: "/world/world_demo/model/tugbot/link/camera_back/sensor/color/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (Camera)
- ros_topic_name: "/camera_back/camera/camera_info"
  gz_topic_name: "/world/world_demo/model/tugbot/link/camera_back/sensor/color/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "/camera_front/color/image_raw"
  gz_topic_name: "/world/world_demo/model/tugbot/link/camera_back/sensor/color/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# Color camera info (latched)
- ros_topic_name: "/camera_front/color/camera_info"
  gz_topic_name: "/world/world_demo/model/tugbot/link/camera_back/sensor/color/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# # Depth camera image
# - ros_topic_name: "/camera_front/depth/image_raw"
#   gz_topic_name: "/world/world_demo/model/tugbot/link/camera_back/sensor/depth/image"
#   ros_type_name: "sensor_msgs/msg/Image"
#   gz_type_name: "gz.msgs.Image"
#   direction: GZ_TO_ROS

# # Depth camera info (latched)
# - ros_topic_name: "/camera_back/depth/camera_info"
#   gz_topic_name: "/world/world_demo/model/tugbot/link/camera_back/sensor/depth/camera_info"
#   ros_type_name: "sensor_msgs/msg/CameraInfo"
#   gz_type_name: "gz.msgs.CameraInfo"
#   direction: GZ_TO_ROS